### ISSUE TITLE
Symmetrical or asymmetrical problems

### ISSUE THREAD

**Issue by Wikunia** [evanfields/TravelingSalesmanHeuristics.jl#17]
Hey I'm wondering whether you intend to further develope this package and if so whether you think it's more for symmetric TSPs or asymmetric ones. If you care about only symmetric ones I would like to make a PR to improve the speed of 2-opt and maybe implement the general k-opt.
Otherwise it might be reasonable to define it somehow whether a problem is symmetric or not and then handle it with different functions.

**Comment by evanfields** [comment]
I definitely intend to maintain it indefinitely, and welcome any help with maintenance or new features! Currently active feature development isn't high on my to-do list, but definitely there's more that can be included.

I've had the thought before that we should have a type `AbstractTSPProblem` (or similar nomenclature) with subtypes like `GeneralAsymmetricTSP`, `SymmetricTSP`, `MetricTSP`, `PlanarEuclideanTSP`, etc. Then instead of passing distance matrices around, the user would create a problem instance and pass that. Any method/heuristic can always default to a general asymmetric implementation, but as you note this would allow dispatching on problem type to get speed improvements or specialized heuristics.

I will note that the primary design goals of this package are that it's general and easy to use. Therefore, while I would be excited to see improved functionality for specialized types of problems, I don't want to limit the type of problems we can handle or force the user to convert between problem types.

What do you think?

**Comment by Wikunia** [comment]
Sure that sounds like a good plan. I found that you completely calculate the tour in 2-opt every time which isn't necessary for both symmetric and asymmetric TSPs.
For symmetric ones even the reversed parts don't have to be calculated obviously.

**Comment by evanfields** [comment]
You're right, excessive calculations of path costs for 2-opt. Feel encouraged to open a PR! I also wonder whether there's a smarter way to order all the possible 2-opt swaps. Right now the ordering starts with reversing longer segments of the path, which presumably could lead to larger cost reductions and faster convergence, but there's probably a clever heuristic to improve that.

**Comment by Wikunia** [comment]
I don't want to open a PR yet but you might wanna have a look at the current status:
https://github.com/Wikunia/TravelingSalesmanHeuristics.jl
I've added an instance with 280 cities and there the symmetric one is about 50 times faster.
Normally you would only consider a couple of neighbors for doing 2-opt I would say.

**Comment by evanfields** [comment]
Hey @Wikunia just wanted to let you know I've been thinking about this package recently so might make some enhancements soon. No definite timetable or anything but if you wanted to get a PR in before I change stuff, soon is the time :)

Your point about efficiency in two-opt costs, especially for symmetric cases, is very well taken!

**Comment by Wikunia** [comment]
Thanks for the update. I think I'll wait til you make your enhancements then and have a look afterwards. What kind of enhancements do you plan?

**Comment by evanfields** [comment]
I think the most important thing is the `TSPInstance` type (with automatic conversion from a raw distance matrix) that contains information about e.g. whether a problem is symmetric, metric, etc.

I'm not sure if it's best to encode that information with flags, e.g.
```
struct TSPInstance
    distmat
    symmetric::Bool
end
```

or the type hierarchy, e.g.
```
abstract type AbstractTSPInstance end
struct SymmetricTSPInstance
    distmat
end
```

The latter seems nice because it allows automatically picking problem appropriate methods via dispatch. And it's easy to implement if the only problem classes are "symmetric" and "general". But I worry that it becomes a nightmare when there are overlapping/hierarchical problem classes like metric, symmetric, Euclidean, planar, nonnegative, ... In contrast, the former simpler system requires "manual dispatch" to pick methods but it's easy to just add boolean flags to the type definition.

**Comment by evanfields** [comment]
I'll go ahead and close this since we now have a few specialized methods for symmetric instances, importantly including 2-opt.
